version: '3.9'

services:

  social-media-posts:
    container_name: flask_app
    build:
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - db
    env_file: .env

  mongo:
    container_name: mongo
    image: mongo:6.0.2
    hostname: mongo
    environment:
      - MONGO_INITDB_DATABASE=social_media_posts_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./.database/mongodb:/data/db
    ports:
      - '27019:27017'
    networks:
      - db

networks:
  db:
    driver: bridge